### ISSUE TITLE
Link to RSS feed is broken

### ISSUE THREAD

**Issue by marcus-nl** [flowable/flowable.github.io#1]
On http://www.flowable.org/blog/:

`<link rel="alternate" type="application/rss+xml" title="Flowable" href="https://flowable.github.io/feed.xml">`

https://flowable.github.io/feed.xml redirects to http://www.flowable.org/feed.xml, which gives a 404:

> Page Not Found
> We couldn't find what you were looking for.
> 
> Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

**Comment by yvoswillens** [comment]
Thanks for pointing that out. 
Is fixed now.
